### ISSUE TITLE
Vignette describing benchmarks

### ISSUE THREAD

**Issue by jknowles** [csgillespie/benchmarkme#12]
I think it would be really helpful to have a package vignette that explains each benchmark in detail using the details from the original source of the benchmark. I know this would make it easier for labs and system builders to include write-ups of these benchmarks in their discussion of machine/architecture performance differences. 

Would this be something you think is appropriate? I could write something up and PR it.

**Comment by csgillespie** [comment]
That would be excellent. I've created a brief description at 

https://github.com/csgillespie/benchmarkme-data/tree/master/inst/shinyapps_io

for the shiny app, but it lacks (at lot of detail).
