### ISSUE TITLE
Parallel documentation

### ISSUE THREAD

**Issue by csgillespie** [csgillespie/benchmarkme#13]
Following #11 

 - Update associated plot methods
 - Update README
 - Update vignette
 - Update shiny app

**Comment by jknowles** [comment]
GitHub still baffles me at times.

Do you want help incorporating these changes? I'm happy to take a task or two if it is easier for you.

**Comment by csgillespie** [comment]
Yes please!

The first point is the hardest. What's the best way of displaying cores?

The two possibilities are:

 * Just divide the time by the number of cores to get a single core value; perhaps a ggplot2 graph with colour on cores?
 * Concentrate on the relative time. So use the time for a single core to normalise multiple cores

**Comment by jknowles** [comment]
Lot's of good ideas here. Let me craft a couple. I think people are generally interested in the efficiency of the scale-up vs. the theoretical scale-up -- so what percentage of 16x improvement does 16 cores get me? Then there is also an interest in the overall performance in seconds of a given operation at 16 cores too.

**Comment by csgillespie** [comment]
Simplified things. The benchmark plot conditions on test_group and cores.
