### ISSUE TITLE
get_linear_algebra() does not detect Intel MKL

### ISSUE THREAD

**Issue by ck37** [csgillespie/benchmarkme#15]
Hello,

It looks like get_linear_algebra() does not detect Intel MKL blas/lapack when R is compiled to use that - it just returns character(0) for $blas and  $lapack.

Looks like it should be an easy fix to detect one of the MKL libraries though:

<img width="570" alt="screen shot 2017-09-23 at 12 34 28 pm" src="https://user-images.githubusercontent.com/50770/30776472-f6eb27fc-a05b-11e7-9bdb-de7c27787f1d.png">

This is using R 3.4.2-beta, Intel MKL 2015.6.233, and gcc 4.8.5.

(Here are the instructions I used to compile R with MKL on my cluster: https://github.com/ck37/savio-xsede-notes/blob/master/compile-R.md)

Cheers,
Chris

**Comment by ck37** [comment]
Confirmed on another cluster as well (XSEDE bridges), this time with a more recent MKL and slightly different .so files displayed. Looks like libmkl_core.so might be the best one to look for, or just "libmkl".

```bash
[ck37@br005 3-analysis]$ lsof -p 17013 | grep libmkl
R       17013 ck37  mem    REG   0,42  28137653   54600213 /opt/intel/compilers_and_libraries_2017.4.196/linux/mkl/lib/intel64_lin/libmkl_core.so (br001.opa.bridges.psc.edu:/nfs/opt/intel)
R       17013 ck37  mem    REG   0,42  28634975   54600196 /opt/intel/compilers_and_libraries_2017.4.196/linux/mkl/lib/intel64_lin/libmkl_intel_thread.so (br001.opa.bridges.psc.edu:/nfs/opt/intel)
R       17013 ck37  mem    REG   0,42   9734508   54600205 /opt/intel/compilers_and_libraries_2017.4.196/linux/mkl/lib/intel64_lin/libmkl_intel_lp64.so (br001.opa.bridges.psc.edu:/nfs/opt/intel)
```

**Comment by csgillespie** [comment]
Thanks for the report. So in the above code, what should be returned for blas & lapack?

Thanks

**Comment by ck37** [comment]
I think "mkl" would be reasonable - that is what R shows in ./configure when building from source.

**Comment by csgillespie** [comment]
Do you `mkl` for both blas & lapack?

I just noticed, but does the `lp` in `libmkl_intel_lp64.so` stand for lapack?

**Comment by ck37** [comment]
Yep it's used for both blas & lapack. Not sure about intel_lp64 but that
makes sense.

**Comment by csgillespie** [comment]
Would you try https://gist.github.com/csgillespie/b0ddf5b54d806e8b3c02d236ebf5ecdf

**Comment by ck37** [comment]
Trying it on another system it looks like there is a different lapack path, so that current proposed grep search would need to be modified a bit:

```bash
/global/software/sl-6.x86_64/modules/langs/intel/2015.6.233/mkl/lib/intel64/libmkl_gf_lp64.so
```

**Comment by csgillespie** [comment]
Thanks. I've updated the blas detection in the latest GitHub version. It should pick up your configuration. Would you check when you have a minute?

**Comment by csgillespie** [comment]
Using sessionInfo should return the correct lib
