### ISSUE TITLE
Matrix size in bm_matrix_cal_lm

### ISSUE THREAD

**Issue by dmbates** [csgillespie/benchmarkme#17]
In the code the matrix is of size `2000x2000` but the verbose result describes the matrix as being of size `3000x3000`.

Also, for linear regression it is more common to have a rectangular model matrix with more rows than columns.  You may want to use, say, 10000 x 1000.

**Comment by csgillespie** [comment]
Fixed in https://github.com/csgillespie/benchmarkme/commit/859bbc431b423597913fef9cd9d577414d232a9c
