### ISSUE TITLE
package ‘benchmarkme’ is not available (for R version 3.4.4)

### ISSUE THREAD

**Issue by alecz20** [csgillespie/benchmarkme#20]
I am trying to install the `benchmarkme` package on the R that installs on Ubuntu 16.04 from the cran repository:

```
> install.packages("benchmarkme")
Installing package into ‘/home/alex/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
Warning message:
package ‘benchmarkme’ is not available (for R version 3.4.4)
```

I was able to install it on the R version (3.5.2) that comes from cran for Ubuntu 18.04.

Is the `benchmarkme` package supposed to install on R 3.4.4, or is 3.5.x required?
If it is, it should be clearly mentioned in the README.

**Comment by csgillespie** [comment]
Good point. Update the README.
