### ISSUE TITLE
System details fails when package not loaded

### ISSUE THREAD

**Issue by dipterix** [csgillespie/benchmarkme#21]
I try to run `benchmarkme` without loading the package and it faild
```r
benchmarkme::get_sys_details()
```

```
> benchmarkme::get_sys_details()
Error in get("benchmark_std", envir = globalenv()) : 
  object 'benchmark_std' not found
```

Also why not use `1Mb=1024KB`, or is there any place where I can set the option?

**Comment by csgillespie** [comment]
Thanks for the report. Fixed the bug, but probably won't update CRAN for a few weeks.

In the meantime, 

```
library(benchmarkme)
get_sys_details()
```
works in the current CRAN version.
