### ISSUE TITLE
`get_ram` not working on Windows 10

### ISSUE THREAD

**Issue by xiaodaigh** [csgillespie/benchmarkme#25]
When I run `get_ram` it returns `NA B`.

Here is my `sessionInfo()`

```
R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.3 tools_3.5.3   
```

**Comment by csgillespie** [comment]
Could you run 
```
system("wmic MemoryChip get Capacity", intern=TRUE)
```
and tell me what that returns?

**Comment by xiaodaigh** [comment]
`"Capacity     \r" "17179869184  \r" "17179869184  \r" "17179869184  \r" "17179869184  \r" "\r"   `

**Comment by csgillespie** [comment]
Thanks. Do you 16Gb of RAM or 4 * 16GB?

**Comment by xiaodaigh** [comment]
4 * 16G

**Comment by tylerburleigh** [comment]
I also get `NA B` and `system("wmic MemoryChip get Capacity", intern=TRUE)` returns `[1] "Capacity    \r" "4294967296  \r" "4294967296  \r" "\r"`. My machine has 8GB, so 2x4GB chips.

**Comment by xiaodaigh** [comment]
this works for me

```r
system('grep MemTotal /proc/meminfo', intern = TRUE)
l = strsplit(a, " ")[[1]]
l = as.numeric(l[length(l)-1])
ram_size = l/1024^2
```

In fact, I have used this in the disk.frame package.

**Comment by csgillespie** [comment]
@xiaodaigh Does that work under windows 7 and 10?

**Comment by xiaodaigh** [comment]
Windows 10 but haven't tested on Windows 7.

**Comment by csgillespie** [comment]
Thanks everyone. I've added the method proposed by @xiaodaigh and used the previous method as a fallback.

**Comment by jonathonkuntz** [comment]
I am also having the same problem where Get_ram() produces “NA B”

I used your code:

> system("wmic MemoryChip get Capacity", intern=TRUE)

With an output of: 

 "Capacity \r" "17179869184 \r" "17179869184 \r" “\r”

This checks out since I have two 16 gb chips.

**Comment by wiesehahn** [comment]
I run into the same problem under windows 10 with package version 1.0.7

**Comment by gxc251** [comment]
Same here under Windows 10, package version 1.0.7, and R version 4.1.0
system("wmic MemoryChip get Capacity", intern=TRUE)
[1] "Capacity     \r" "17179869184  \r" "17179869184  \r" "\r"
get_ram()
NA B
