### ISSUE TITLE
Missing import: Error in globalVariables(c("a", "b", "ans")) : could not find function "globalVariables"

### ISSUE THREAD

**Issue by HenrikBengtsson** [csgillespie/benchmarkme#28]
Hi. The

https://github.com/csgillespie/benchmarkme/blob/8ee0d3a1c25887407647db352082f1d2d87b36a3/R/benchmark_matrix_calculations.R#L1

lacks a `@importFrom utils globalVariables` or needs to be specified as:
```
utils::globalVariables(...)
```

I'm getting errors on this when revdep checking several packages, e.g. `R CMD check` on data.frame reports:
```r
Error in globalVariables(c("a", "b", "ans")) : 
  could not find function "globalVariables"
Error: unable to load R code in package ‘benchmarkme’
Execution halted
```

PS. I've spotted many other packages that forget to import `globalVariables()`, `setMethod()`, ...

**Comment by csgillespie** [comment]
Thanks
