### ISSUE TITLE
Possibility to access the benchmark dataset

### ISSUE THREAD

**Issue by JSEHV** [csgillespie/benchmarkme#29]
Is it possible to acces the benchmark dataset, so the results of the system and that of the systems which it is compared against can be downloaded/accessed. This way it gives a better understanding where the system actually is ranked. Just dots on a plot don't say that much.

**Comment by csgillespie** [comment]
The raw data is available via https://github.com/csgillespie/benchmarkme-data

---

I'll update the package tomorrow.
