### ISSUE TITLE
Problem to install benchemarkme

### ISSUE THREAD

**Issue by oliviervg** [csgillespie/benchmarkme#3]
Thank you for this promising package, 
however, I was not able to install the package (windows 64, R studio 0.99.436, R version 3.1.2 (2014-10-31)), and I get the following message :

```
> install.packages("benchmarkme")
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  unable to access index for repository http://csgillespie.github.io/drat/bin/windows/contrib/3.1
Installing package into ‘C:/Users/ULB/Documents/R/win-library/3.1’
(as ‘lib’ is unspecified)
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  unable to access index for repository http://csgillespie.github.io/drat/bin/windows/contrib/3.1

   package ‘benchmarkme’ is available as a source package but not as a binary

Warning in install.packages :
  package ‘benchmarkme’ is not available (for R version 3.1.2)
```

Thank you for your help

**Comment by csgillespie** [comment]
Thanks for the feedback. Does

```
install.packages("drat")
drat::addRepo("csgillespie")
install.packages("benchmarkme", type="source")
```

work?

**Comment by oliviervg** [comment]
Thank you for you reply,
Unfortunately, it still does not work :

> install.packages("drat")Warning in install.packages :
>   cannot open: HTTP status was '404 Not Found'
> Warning in install.packages :
>   cannot open: HTTP status was '404 Not Found'
> Warning in install.packages :
>   unable to access index for repository
> http://csgillespie.github.io/drat/bin/windows/contrib/3.1Installing
> package into ‘C:/Users/ULB/Documents/R/win-library/3.1’
> (as ‘lib’ is unspecified)Warning in install.packages :
>   cannot open: HTTP status was '404 Not Found'
> Warning in install.packages :
>   cannot open: HTTP status was '404 Not Found'
> Warning in install.packages :
>   unable to access index for repository
> http://csgillespie.github.io/drat/bin/windows/contrib/3.1trying URL
> 'http://cran.rstudio.com/bin/windows/contrib/3.1/drat_0.1.0.zip'Content
> type 'application/zip' length 70232 bytes (68 Kb)opened URLdownloaded
> 68 Kb
> package ‘drat’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
    C:\Users\ULB\AppData\Local\Temp\Rtmp8MPO94\downloaded_packages

> drat::addRepo("csgillespie")> install.packages("benchmarkme", type="source")Warning in install.packages :
>   cannot open: HTTP status was '404 Not Found'
> Warning in install.packages :
>   cannot open: HTTP status was '404 Not Found'
> Warning in install.packages :
>   unable to access index for repository
> http://csgillespie.github.io/drat/bin/windows/contrib/3.1Installing
> package into ‘C:/Users/ULB/Documents/R/win-library/3.1’
> (as ‘lib’ is unspecified)also installing the dependency ‘httr’
> trying URL 'http://cran.rstudio.com/src/contrib/httr_1.0.0.tar.gz'Content
> type 'application/x-gzip' length 245989 bytes (240 Kb)opened
> URLdownloaded 240 Kb
> trying URL 'http://csgillespie.github.io/drat/src/contrib/benchmarkme_0.1.2.tar.gz'Content
> type 'application/octet-stream' length 11944 bytes (11 Kb)opened
> URLdownloaded 11 Kb
> - installing _source_ package 'httr' ...
>   *\* package 'httr' correctement décompressé et sommes MD5 vérifiées
>   *\* R
>   *\* demo
>   *\* inst
>   *\* preparing package for lazy loading
>   *\* help
>   **\* installing help indices
>   *\* building package indices
>   *\* installing vignettes
>   *\* testing if installed package can be loaded
>   **\* arch - i386
>   Error : package 'httr' is not installed for 'arch = i386'
>   Erreur : le chargement a échoué
>   Exécution arrêtée
>   **\* arch - x64
>   ERROR: loading failed for 'i386'
> - removing 'C:/Users/ULB/Documents/R/win-library/3.1/httr'
>   Warning in install.packages :
>   running command '"C:/PROGRA~1/R/R-31~1.2/bin/x64/R" CMD INSTALL -l
>   "C:\Users\ULB\Documents\R\win-library\3.1"
>   C:\Users\ULB\AppData\Local\Temp\Rtmp8MPO94/downloaded_packages/httr_1.0.0.tar.gz'
>   had status 1
>   Warning in install.packages :
>   installation of package ‘httr’ had non-zero exit status
>   ERROR: dependency 'httr' is not available for package 'benchmarkme'
> - removing 'C:/Users/ULB/Documents/R/win-library/3.1/benchmarkme'
>   Warning in install.packages :
>   running command '"C:/PROGRA~1/R/R-31~1.2/bin/x64/R" CMD INSTALL -l
>   "C:\Users\ULB\Documents\R\win-library\3.1"
>   C:\Users\ULB\AppData\Local\Temp\Rtmp8MPO94/downloaded_packages/benchmarkme_0.1.2.tar.gz'
>   had status 1
>   Warning in install.packages :
>   installation of package ‘benchmarkme’ had non-zero exit status

The downloaded source packages are in
    ‘C:\Users\ULB\AppData\Local\Temp\Rtmp8MPO94\downloaded_packages’

Olivier Van Grembergen

2015-12-01 17:47 GMT+01:00 Colin Gillespie notifications@github.com:

**Comment by csgillespie** [comment]
Thanks. 

What about

```
install.packages(c("drat", "httr", "Matrix"))
drat::addRepo("csgillespie")
install.packages("benchmarkme", type="source")
```

**Comment by oliviervg** [comment]
Yes ! it works !
Thank you for your work !

Olivier Van Grembergen

2015-12-01 18:00 GMT+01:00 Colin Gillespie notifications@github.com:
