### ISSUE TITLE
Problem when uploading benchmark results on OSX El Capitan

### ISSUE THREAD

**Issue by sjmgarnier** [csgillespie/benchmarkme#4]
MacBook Pro (Retina, 13-inch, Early 2015)
OSX 10.11.1 (15B42)

> > upload_results(res)
>    I'm having trouble detecting your RAM. So try a number of things to help future versions
>    awk: can't open file /proc/meminfo
>     source line number 1
>    sh: wmic: command not found
>    Error in system("wmic MemoryChip get Capacity", intern = TRUE) : 
>      error in running command
>    In addition: Warning message:
>    running command 'awk '/MemFree/ {print $2}' /proc/meminfo' had status 2 `

**Comment by csgillespie** [comment]
Would you run 

```
dput(system('system_profiler -detailLevel mini | grep "  Memory:"', intern=TRUE))
```

I don't have easy access to a MAC

**Comment by mkuhn** [comment]
I also get an error, but only the first line (I'm having trouble...). The dput command takes a while and then returns:

```
"      Memory: 16 GB"
```

**Comment by csgillespie** [comment]
Thanks for reporting. Hopefully this should now work.

Regarding the speed, 

```
system('system_profiler -detailLevel mini`)
```

is the reason. But I don't know of any other way of detecting the RAM.
