### ISSUE TITLE
get_ram() returns NA B on Windows 10/11 Pro machines

### ISSUE THREAD

**Issue by xiaodaigh** [csgillespie/benchmarkme#44]
`get_ram()` returns `NA B` but `benchmarkme:::get_windows_ram()` gives `"17179869184  \r" "17179869184  \r" "17179869184  \r" "17179869184  \r" "\r"    `

```
sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    
system code page: 65001
```

**Comment by csgillespie** [comment]
I updated the GitHub version about a week ago. Does that work for you? If so, I'll update the CRAN version

**Comment by xiaodaigh** [comment]
Nope. Still get NA B

**Comment by csgillespie** [comment]
Any chance you could try https://github.com/csgillespie/benchmarkme/blob/main/R/get_ram.R#L1 and see if there's  a fix?

I don't use Windows

**Comment by xiaodaigh** [comment]
issue seems to be https://github.com/csgillespie/benchmarkme/blob/6a342e41dde9eb8a7c077ad343be299f0afdca17/R/clean_ram_output.R#L15

Wonder why it filters out `length(ram) > 1`? I will make a PR

**Comment by mroddc** [comment]
I keep getting this issue too. I'm on Windows 10, R 4.2.0   This was also happening on 4.1 versions.  It causes an issue with the disk.frame package, which depends on get_ram().    As a result, disk.frame is inefficient because it defaults to 16gb 

Has there been any update?

 get_ram()
	 Unable to detect your RAM. # nocov 
            Please raise an issue at https://github.com/csgillespie/benchmarkme

**Comment by mroddc** [comment]
awesome.  I can confirm that it is working on my R environment, RStudio,
Windows 10. Thanks!
