### ISSUE TITLE
Error when package is not attached

### ISSUE THREAD

**Issue by YvesCR** [csgillespie/benchmarkme#8]
Hi Gilles, I saw you at LondonR yesterday, it was a good talk.

I have installed the package benchmarkme but there is a light issue:
you have to attach the library and can't just access the function through the double colon.

    install.packages("benchmarkme") # ok

     benchmarkme::benchmark_std()
    # Programming benchmarks (5 tests):
    Error in FUN(X[[i]], ...) : could not find function "bm_prog_fib"

    library(benchmarkme)
    benchmark_std() # ok

**Comment by csgillespie** [comment]
Thanks for the report; I think it must be problem with lazy loading. 

I don't have an obvious fix at the moment, but I'll have a think about it.
